import { Roboto, Archivo_Black } from 'next/font/google';
import './globals.css';
import { AuthProvider } from '@/context/AuthContext';

const roboto = Roboto({
	variable: '--font-roboto',
	subsets: ['latin'],
	display: 'swap',
});

const archivoBlack = Archivo_Black({
	variable: '--font-archivo-black',
	subsets: ['latin'],
	display: 'swap',
	weight: '400',
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body
				className={`${roboto.variable} ${archivoBlack.variable} antialiased`}
			>
				<AuthProvider>{children}</AuthProvider>
			</body>
		</html>
	);
}
